In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
datasets = [
    [0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [1, 0, 0, 0, 1],
    [2, 1, 0, 0, 1],
    [2, 2, 1, 0, 1],
    [2, 2, 1, 1, 0],
    [1, 2, 1, 1, 1],
    [0, 1, 0, 0, 0],
    [0, 2, 1, 0, 1],
    [2, 1, 1, 0, 1],
    [0, 1, 1, 1, 1],
    [1, 1, 0, 1, 1],
    [1, 0, 1, 0, 1],
    [2, 1, 0, 1, 0]
]



datasets = np.array(datasets, dtype=float)
datasets

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [2., 1., 0., 0., 1.],
       [2., 2., 1., 0., 1.],
       [2., 2., 1., 1., 0.],
       [1., 2., 1., 1., 1.],
       [0., 1., 0., 0., 0.],
       [0., 2., 1., 0., 1.],
       [2., 1., 1., 0., 1.],
       [0., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 0., 1., 0., 1.],
       [2., 1., 0., 1., 0.]])

In [ ]:
x = datasets[:, :4]
y = datasets[:, -1]
print(x)
print(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [2. 2. 1. 0.]
 [2. 2. 1. 1.]
 [1. 2. 1. 1.]
 [0. 1. 0. 0.]
 [0. 2. 1. 0.]
 [2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [1. 1. 0. 1.]
 [1. 0. 1. 0.]
 [2. 1. 0. 1.]]
[0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0.]


In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(20, activation='relu', input_dim=4),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss=tf.keras.losses.Huber(), optimizer='adam', metrics=['acc'])
model.summary()
model.fit(x, y, epochs=500)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                100       
                                                                 
 dense_1 (Dense)             (None, 10)                210       
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 321 (1.25 KB)
Trainable params: 321 (1.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/500
1/1 [==============================] - 1s 920ms/step - loss: 0.1218 - acc: 0.4286
Epoch 2/500
1/1 [==============================] - 0s 10ms/step - loss: 0.1214 - acc: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 11ms/step - loss: 0.1210 - acc: 0.5000
Epoch 4/50

In [ ]:
# 1 = BOLEH , 0 = TIDAK
data_test = [
    [0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [1, 0, 0, 0, 1],
    [2, 1, 0, 0, 1],
    [2, 2, 1, 0, 1],
    [2, 2, 1, 1, 0],
    [1, 2, 1, 1, 1],
    [0, 1, 0, 0, 0],
    [0, 2, 1, 0, 1],
    [2, 1, 1, 0, 1],
    [0, 1, 1, 1, 1],
    [1, 1, 0, 1, 1],
    [1, 0, 1, 0, 1],
    [2, 1, 0, 1, 0]
]

for data in data_test:
  print({ 'data': data })
  x_test = data[:4]
  predicted = model.predict(np.array([x_test], dtype=float))[0][0]
  print(predicted)
  if(predicted >= 0.7):
    print('Boleh melaut')
  elif(predicted >= 0.4):
    print('Hati-hati saat melaut')
  else:
    print('Tidak boleh melaut')
  print('===========================================')

{'data': [0, 0, 0, 0, 0]}
1/1 [==============================] - 0s 358ms/step
0.06620659
Tidak boleh melaut
{'data': [0, 0, 0, 1, 0]}
1/1 [==============================] - 0s 69ms/step
0.062903695
Tidak boleh melaut
{'data': [1, 0, 0, 0, 1]}
1/1 [==============================] - 0s 37ms/step
0.8910389
Boleh melaut
{'data': [2, 1, 0, 0, 1]}
1/1 [==============================] - 0s 85ms/step
0.90964687
Boleh melaut
{'data': [2, 2, 1, 0, 1]}
1/1 [==============================] - 0s 67ms/step
0.94025004
Boleh melaut
{'data': [2, 2, 1, 1, 0]}
1/1 [==============================] - 0s 169ms/step
0.51108414
Hati-hati saat melaut
{'data': [1, 2, 1, 1, 1]}
1/1 [==============================] - 0s 70ms/step
0.9299614
Boleh melaut
{'data': [0, 1, 0, 0, 0]}
1/1 [==============================] - 0s 48ms/step
0.063563086
Tidak boleh melaut
{'data': [0, 2, 1, 0, 1]}
1/1 [==============================] - 0s 131ms/step
0.950929
Boleh melaut
{'data': [2, 1, 1, 0, 1]}
1/1 [=======================

In [ ]:
x_test_lagi = [1,0,1,1]
predictable = model.predict(np.array([x_test_lagi], dtype=float))[0][0]
print(predictable)
if(predictable >= 0.7):
  print('Boleh melaut')
elif(predictable >= 0.4):
  print('Hati-hati saat melaut')
else:
  print('Tidak boleh melaut')

1/1 [==============================] - 0s 92ms/step
0.7387111
Boleh melaut


In [ ]:
data_ical_wibu = [
    [0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [1, 0, 0, 0, 1],
    [2, 1, 0, 0, 1],
    [2, 2, 1, 0, 1],
    [2, 2, 1, 1, 0],
    [1, 2, 1, 1, 1],
    [0, 1, 0, 0, 0],
    [0, 2, 1, 0, 1],
    [2, 1, 1, 0, 1],
    [0, 1, 1, 1, 1],
    [1, 1, 0, 1, 1],
    [1, 0, 1, 0, 1],
    [2, 1, 0, 1, 0]
]

Outlook = [ical_wibu[0] for ical_wibu in data_ical_wibu]
Temp = [ical_wibu[1] for ical_wibu in data_ical_wibu]
Humidity = [ical_wibu[2] for ical_wibu in data_ical_wibu]
Wind = [ical_wibu[3] for ical_wibu in data_ical_wibu]
Decision = [ical_wibu[4] for ical_wibu in data_ical_wibu]

print(Outlook)
print(Temp)
print(Humidity)
print(Wind)
print(Decision)

[0, 0, 1, 2, 2, 2, 1, 0, 0, 2, 0, 1, 1, 2]
[0, 0, 0, 1, 2, 2, 2, 1, 2, 1, 1, 1, 0, 1]
[0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0]
[0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1]
[0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0]


In [ ]:
model.save('fail_decision.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
